name: News scrape (Ubuntu 24.04)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # 毎日15:00 JST (=06:00 UTC) に実行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps for Chrome/Selenium (noble)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libu2f-udev \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            unzip
          # 注意: noble では libasound2 → libasound2t64 に置き換え
          #       libgconf-2-4 は存在しないため不要

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements (1).txt"

      - name: Run scraper
        env:
          KEYWORD: "${{ vars.KEYWORD || '日産' }}"
          SPREADSHEET_ID: "1XvqKjCqYx9iCuUwIDaOUT1C_pCkj4kPx5DVJPjsLSxE"
          GCP_SERVICE_ACCOUNT_KEY: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
        run: |
          python "main_combined.py"
