name: News scrape (Ubuntu 24.04)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # 毎日15:00 JST (=06:00 UTC) に実行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps for Chrome/Selenium (noble)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libu2f-udev \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            unzip
          # 注意: noble では libasound2 → libasound2t64 に変更
          #       libgconf-2-4 は存在しないため不要

      # 必要な場合のみ有効化してください（通常は不要）
      # - name: Install Google Chrome (optional)
      #   run: |
      #     wget -qO- https://dl.google.com/linux/linux_signing_key.pub | \
      #       sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-keyring.gpg
      #     echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] \
      #       http://dl.google.com/linux/chrome/deb/ stable main" | \
      #       sudo tee /etc/apt/sources.list.d/google-chrome.list
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          KEYWORD: "${{ vars.KEYWORD || '日産' }}"
          SPREADSHEET_ID: "1XvqKjCqYx9iCuUwIDaOUT1C_pCkj4kPx5DVJPjsLSxE"
          GCP_SERVICE_ACCOUNT_KEY: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
        run: |
          python "main_combined.py"
