name: Yahoo News Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # 毎日15:00 JST (=06:00 UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (Chromium + Driver)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libu2f-udev \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            unzip \
            chromium \
            chromium-driver
          # 確認ログ
          which chromium-browser || true
          which chromium || true
          which chromedriver || true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests gspread oauth2client

      - name: Run scraper
        env:
          SPREADSHEET_ID: "1XvqKjCqYx9iCuUwIDaOUT1C_pCkj4kPx5DVJPjsLSxE"
          GCP_SERVICE_ACCOUNT_KEY: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
        run: |
          python "main_combined.py"
